# Generated by Django 5.1.3 on 2024-11-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_custom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Web Development", "Web"),
                    ("Full Stack Development", "Full Stack"),
                    ("Game Development", "Game"),
                    ("Agile and Project Management", "Project Management"),
                    ("Hackathon Projects", "Hackathon"),
                ],
                default="All",
                max_length=100,
            ),
        ),
    ]
