# Generated by Django 5.1.3 on 2024-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_custom", "0006_alter_project_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
