# Generated by Django 5.1.3 on 2024-11-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_custom", "0007_project_project_date_alter_project_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="role_details", field=models.TextField(),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_custom.project",
                    ),
                ),
            ],
        ),
    ]
