# Generated by Django 5.1.3 on 2024-11-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_custom", "0009_alter_project_project_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="project_image",),
    ]
